[package]
name = "tiberius_derive_bin"
version = "0.1.0"
authors = ["mlcruz1 <mlcruz@inf.ufrgs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiberius_derive = { path = "tiberius-derive" }
tiberius = "0.5.12"
